CREATE TABLE `supply_chain_indices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` varchar(10) NOT NULL,
	`tpu_index` varchar(20),
	`us_trade_tpu` varchar(20),
	`tpu_change_3m` varchar(20),
	`bls_import_price` varchar(20),
	`bls_change` varchar(20),
	`hrc_price` varchar(20),
	`hrc_mom` varchar(20),
	`hrc_yoy` varchar(20),
	`lme_aluminum` varchar(20),
	`lme_al_mom` varchar(20),
	`lme_al_yoy` varchar(20),
	`cme_copper` varchar(20),
	`cme_cu_mom` varchar(20),
	`cme_cu_yoy` varchar(20),
	`diesel_price` varchar(20),
	`diesel_change` varchar(20),
	`cass_expenditure` varchar(20),
	`cass_change` varchar(20),
	`wci_ocean` varchar(20),
	`wci_change` varchar(20),
	`source` varchar(200),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `supply_chain_indices_id` PRIMARY KEY(`id`)
);
